export const TAB = 9                // \t
export const NEW_LINE = 10          // \n
export const CARRIAGE_RETURN = 13   // \r
export const SPACE = 32             //
export const DOUBLE_QUOTE = 34      // "
export const COMMA = 44             // ,
export const COLON = 58             // :
export const SQUARE_OPEN = 91       // [
export const SQUARE_CLOSE = 93      // ]
export const CURLY_OPEN = 123       // {
export const CURLY_CLOSE = 125      // }
export const ZERO = 48
export const DOT = 46
export const EXPONENT = 101
export const EXPONENT_UPPER = 69
export const PLUS = 43
export const MINUS = 45